### PR TITLE
Update 05_Simple_Contact_Form.md

### PR DESCRIPTION
**Pull request by erangaddd**
Fixed type in line 32 and added
use SilverStripe\Forms\TextareaField;

### CODE REVIEW

**Review by michalkleiner — APPROVED** [review]
Thanks @erangaddd

**Comment by michalkleiner** [comment]
@GuySartorelli is this gonna deploy auto-magically or does it need to be pushed also to `5`?

**Comment by GuySartorelli** [comment]
5.1 is the branch docs currently pull from - and there's a GitHub action that should trigger whenever a pr is merged into 5.1 to redeploy. So it _should_ deploy automatically.

**Comment by erangaddd** [comment]
@michalkleiner you are welcome. @GuySartorelli yes it is in production now.

**Pull request merged**
