### PR TITLE
4.0 changelog example for DBComposite missing return

### PR DESCRIPTION
**Pull request by christopherdarling**

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Can you please target this at the `4.12` branch so it can take effect immediately after merging?
Otherwise this won't actually change anything until the 4.13 release.

**Comment by christopherdarling** [comment]
@GuySartorelli  done :-)

**Comment by GuySartorelli** [comment]
@christopherdarling looks like you've brought along a few extra commits accidentally. Can you please rebase? Or if that doesn't work, you can do the following to get your changes in this PR without all the extra commits:

1. `git checkout 4.12 && git pull`
1. `git branch -D patch-1` to delete your local copy of the PR branch
1. `git checkout -b patch-1` so you have a new branch based on 4.12 with the same name as the PR branch
1. `git cherry-pick aa0bfc63ae` to get your changes into your new branch
1. `git push <remote> patch-1 --force-with-lease` to update this PR (replace `<remote>` with the name of your remote)

**Comment by christopherdarling** [comment]
@GuySartorelli sorry I dont have the repository here locally to do that. I've recreated a PR at #124 though.

**Pull request closed without merging**
