### PR TITLE
Update a example code comment

### PR DESCRIPTION
**Pull request by n8-dev**
Comment in code example didn't make sense

### CODE REVIEW

**Review by michalkleiner — APPROVED** [review]

**Comment by michalkleiner** [comment]
@GuySartorelli how low a version we should target this at?

**Comment by GuySartorelli** [comment]
IMO it's not suuuper important to target the correct branch for small changes like this - but ideally any change that is a valid change for CMS 4 docs should target `4.13` and be merged up from there.
If this only affect CMS 5 docs then `5.1` is correct.

**Comment by n8-dev** [comment]
Let me know if I can help; or rather how to make this better in the future.

I just clicked the edit on github button whilst reading docs as well.

**Review by GuySartorelli — APPROVED** [review]
As mentioned, this is fine where it is. Thanks for the edit.

> Let me know if I can help; or rather how to make this better in the future.

If you want to always target the correct branch, there's some guidance about that in [the contributing docs](https://docs.silverstripe.org/en/5/contributing/documentation/#branches-and-commit-messages) - but again, for small changes like this it doesn't matter too much.

**Pull request merged**
