### PR TITLE
DOC Update react injector docs to work

### PR DESCRIPTION
**Pull request by GuySartorelli**
Reapplies the changes to graphql injector docs that were (meant to be) [reverted](https://github.com/silverstripe/developer-docs/pull/199) (along with any new changes I found that were required)

## NOTE
The revert commit was not completed correctly. It was meant to revert the entirety of https://github.com/silverstripe/developer-docs/pull/187 and https://github.com/silverstripe/developer-docs/pull/197, but failed to do so!
That's okay because this commit would have partially reinstated those PRs anyway.

Make sure you test and review _the entirety_ of the graphql/javascript code from `## Using Injector to customise GraphQL queries` to the end of the file. That includes both the graphql 3 _and_ graphql 4 sections! _ALL_ of that is in scope for this PR.

## Requires extra admin PR also
- https://github.com/silverstripe/silverstripe-admin/pull/1498

## Issue
- https://github.com/silverstripe/developer-docs/issues/62

### CODE REVIEW

**Comment by sabina-talipova** [comment]
Could we also fix this small spelling issue `cient` to `client`.
https://github.com/silverstripe/developer-docs/blob/1a9525dec9596d59090a4f2606e0ee3da0d19b57/en/02_Developer_Guides/15_Customising_the_Admin_Interface/07_ReactJS_Redux_and_GraphQL.md?plain=1#L1412

And small question: why we use somewhere `app/client` and in another places `my-module/client`?

**Comment by GuySartorelli** [comment]
> why we use somewhere `app/client` and in another places `my-module/client`?

It's to distinguish between the two contexts this documentation is bouncing between - there's a module which provides the notes components and the actual `DataObject` implementation, and then there's some app project which is customising that component by adding the priority field.

Really this whole section of docs needs to be reconsidered, probably being split into a more traditional "here is the API and how it works" and then these examples should be moved into a "how to" section and fleshed out a bit more. But that's not in scope for this PR where I'm just trying to make sure the examples work at all.

**Comment by sabina-talipova** [comment]
> Really this whole section of docs needs to be reconsidered, probably being split into a more traditional "here is the API and how it works" and then these examples should be moved into a "how to" section and fleshed out a bit more. But that's not in scope for this PR where I'm just trying to make sure the examples work at all.

We should, probably, update this section. Since information presented in `## Using Injector to customise GraphQL queries` section is not enough to use it as an example for testing.

**Review by sabina-talipova — CHANGES_REQUESTED** [review]
Could you fix spelling mistake `cient` to `client `
https://github.com/silverstripe/developer-docs/blob/1a9525dec9596d59090a4f2606e0ee3da0d19b57/en/02_Developer_Guides/15_Customising_the_Admin_Interface/07_ReactJS_Redux_and_GraphQL.md?plain=1#L1412

**Comment by GuySartorelli** [comment]
> We should, probably, update this section. Since information presented in `## Using Injector to customise GraphQL queries` section is not enough to use it as an example for testing.

I've made a note about this in https://github.com/silverstripe/developer-docs/issues/129, which is about reviewing the structure and general content of front-end related documentation. It falls outside the scope of _this_ PR, which is really just about making the graphql code examples work - not necessarily about making them clear and easy to understand.

In other words, we'll do this in stages:
- Stage one is getting the code example to work at all. That's this PR
- Stage two is restructuring the doc so that the code example and API documentation are separate, and independently easy to follow. That's https://github.com/silverstripe/developer-docs/issues/129

For the purposes of testing _this_ PR, I'll send you the project I used to do so with information about how to use it for testing this PR.

**Comment by GuySartorelli** [comment]
I've fixed the typo.

**Review by sabina-talipova — APPROVED** [review]
LGFM

**Pull request merged**
