### PR TITLE
DOC Add new query trace comment to changelog

### PR DESCRIPTION
**Pull request by GuySartorelli**
## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/11064

### CODE REVIEW

**Review by GuySartorelli — COMMENTED** [review]
Note: The branch this PR is targetting now has a CI action. This PR will need to be force-pushed to run the CI, and the CI must be green before merging.

**Comment by GuySartorelli** [comment]
Rebased and resolved conflicts, lint passes locally.

**Comment by GuySartorelli** [comment]
Rebased and resolved conflicts

**Review by emteknetnz — APPROVED** [review]

**Comment by GuySartorelli** [comment]
Docs updated to reflect changes in the code

**Review by emteknetnz — CHANGES_REQUESTED** [review]
In the main PR I recommended adding enabling via an environment variable, so that should also be documented here

**Comment by GuySartorelli** [comment]
Updated to reference new environment variable

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
