### PR TITLE
DOC Document deprecations for template layer refactor

### PR DESCRIPTION
**Pull request by GuySartorelli**
## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/11322

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Linting failure is unrelated

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Missing SSViewer::execute_template() + SSViewer::execute_string()

**Comment by emteknetnz** [comment]
Still need to add SSViewer::execute_template() + SSViewer::execute_string(), and rebase

**Comment by GuySartorelli** [comment]
Oops! Sorry, I was so focused on updating the code PRs I forgot this had a requested change.
Updated now.

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
