### PR TITLE
Update 05_Simple_Contact_Form.md

### PR DESCRIPTION
**Pull request by erangaddd**

### CODE REVIEW

**Comment by erangaddd** [comment]
use SilverStripe\Forms\TextareaField;

**Comment by erangaddd** [comment]
Update

**Review by erangaddd — COMMENTED** [review]
Added line 
use SilverStripe\Forms\TextareaField;

**Comment by GuySartorelli** [comment]
Thank you for submitting this.

As a matter of house keeping - in future please provide a clear description of what change you're making and why in the PR description, and adhere to our [documented commit message guidelines](https://docs.silverstripe.org/en/5/contributing/documentation/#branches-and-commit-messages).

There is a PHP linting issue in the CI - can you please resolve that?

**Comment by GuySartorelli** [comment]
(oops sorry, didn't mean to close it)

**Comment by erangaddd** [comment]
Thank you for the approval.

**Comment by GuySartorelli** [comment]
@erangaddd It looks like you've pulled through a bunch of commits from the 5 branch. Please [reset your commits](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f) so that this can be merged.

**Pull request closed without merging**
